---

# configure local user

- hosts: all
  become: no

  tasks:

  - name: clone bin project
    git:
      repo: 'https://github.com/mcgarrigle/bin.git'
      dest: bin

  - name: clone nvim project
    git:
      repo: 'https://github.com/mcgarrigle/nvim.git'
      dest: .config/nvim

  - name: configure environment
    shell: ./bin/vm-configure shell
