---
- name: disable selinux
  ansible.posix.selinux:
    state: disabled

- name: packages
  yum:
    name:
    - epel-release
    - yum-utils
    - bash-completion
    - vim
    - neovim
    - ripgrep
    - fd-find
    - tree
    - git
    - tmux
    - python3
    - python3-pip
    - make
    - gcc
    - g++
    - java-latest-openjdk-devel
    - wget
    - rsync
    - lsof
    - netcat
    - wireshark-cli
    - nss-mdns
    - avahi
    - bind-utils
    - cockpit
    - cockpit-podman
    state: present

- name: mdns service
  service:
    name: avahi-daemon.service
    state: started
    enabled: true

- name: cockpit service
  service:
    name: cockpit.socket
    state: started
    enabled: true



- hosts: all
become: no

tasks:

- name: clone bin project
  git:
    repo: 'https://github.com/mcgarrigle/bin.git'
    dest: bin

- name: configure environment
  shell: ./bin/vm-configure shell
